
default: &default
  adapter: postgresql
  encoding: unicode
  host: localhost
  port: 54320
  username: postgres
  password: postgres@123
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: pixcade_backend_development

test:
  <<: *default
  database: pixcade_backend_test

production:
  <<: *default
  database: pixcade_backend_production
  username: pixcade_backend
  password: <%= ENV["PIXCADE_BACKEND_DATABASE_PASSWORD"] %>
